name: Integration Tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  integration-test-no-docker:
    name: Run integration tests against MCP as a binary, invoking docker images for each language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: build python image
        run: |
          docker build -t python-no-root -f docker/python.Dockerfile ./docker

      - name: build rust image
        run: |
          docker build -t rust-no-root -f docker/rust.Dockerfile ./docker

      - name: build javascript image
        run: |
          docker build -t js-no-root -f docker/javascript.Dockerfile ./docker

      - name: Start mcp
        run: |
          cargo build
          cargo run & # nohup

      - name: Wait for port 8000
        run: |
          # Loop until localhost:8000 returns a 200 OK
          timeout 60s bash -c 'until curl -s localhost:8000; do sleep 1; done'

      - name: Test tool list
        run: |
          tool_list=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/list)
          result=$(echo $tool_list | jq -r '.tools  | length')
          if [ $result != "4" ]; then
            echo "Assertion failed: $result"
            exit 1
          fi

      - name: Test python tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_python \
            --tool-arg command=python \
            --tool-arg args='["integration-tests/helloworld.py"]' \
            --tool-arg project_dir=$(pwd))
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi

      - name: Test javascript tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_javascript \
            --tool-arg command=node \
            --tool-arg args='["integration-tests/helloworld.js"]' \
            --tool-arg project_dir=$(pwd))
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi

      - name: Test rust tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_rust \
            --tool-arg command=cargo \
            --tool-arg args='["test"]' \
            --tool-arg project_dir=$(pwd))
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi
  integration-test-with-docker:
    name: Run integration tests against MCP hosted in self-contained docker with languages included in docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: build comprehensive image
        run: |
          docker build -t main-docker -f docker/Dockerfile ./

      - name: Start mcp
        run: |
          docker run -p 8000:8000 \
            -v $(pwd):/app/code_location \
            -e CARGO_TARGET_DIR=/tmp/target \
            -d \
            main-docker

      - name: Wait for port 8000
        run: |
          # Loop until localhost:8000 returns a 200 OK
          timeout 60s bash -c 'until curl -s localhost:8000; do sleep 1; done'

      - name: Test tool list
        run: |
          tool_list=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/list)
          result=$(echo $tool_list | jq -r '.tools  | length')
          if [ $result != "4" ]; then
            echo "Assertion failed: $result"
            exit 1
          fi

      - name: Test python tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_python \
            --tool-arg command=python \
            --tool-arg args='["helloworld.py"]' \
            --tool-arg project_dir=integration-tests)
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi

      - name: Test javascript tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_javascript \
            --tool-arg command=node \
            --tool-arg args='["helloworld.js"]' \
            --tool-arg project_dir=integration-tests)
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi

      - name: Test rust tool call
        run: |
          tool_call=$(npx @modelcontextprotocol/inspector \
            --cli http://localhost:8000/mcp \
            --method tools/call \
            --tool-name run_rust \
            --tool-arg command=cargo \
            --tool-arg args='["test"]' \
            --tool-arg project_dir=.)
          result=$(echo $tool_call | jq -r '.isError ')
          if [ $result != "false" ]; then
            echo "Assertion failed: $result"
            echo "Tool call: $tool_call"
            exit 1
          fi
